openapi: 3.0.3
info:
  title: Product Service API
  description: API for managaing products
  version: '1.0.0'
servers:
  - url: https://mbmmx4ei9e.execute-api.eu-north-1.amazonaws.com/prod
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '1'
                    title:
                      type: string
                      example: 'Car'
                    description:
                      type: string
                      example: 'Fancy car'
                    count:
                      type: number
                      example: 10
                    price:
                      type: number
                      example: 100
  /products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
            example: '1'
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '1'
                  title:
                    type: string
                    example: 'Car'
                  description:
                    type: string
                    example: 'Fancy car'
                  count:
                    type: number
                    example: 10
                  price:
                    type: number
                    example: 100
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product not found
